### ISSUE TITLE
Wondering when the adversarial patch part will be released

### ISSUE THREAD

**Issue by tao-bai** [Muzammal-Naseer/Intriguing-Properties-of-Vision-Transformers#3]

**Comment by Muzammal-Naseer** [comment]
Hi Tao,

Thank you for your interest in our work. 

We optimize adversarial patches by simply replacing CNN with ViTs in the following repo (https://github.com/jhayes14/adversarial-patch). We created untargeted adversarial patches.

We will release the pretrained patches as well.

Regards,
Muzammal

**Comment by tao-bai** [comment]
Got it! Thanks!

**Comment by Beckschen** [comment]
hello Mr. Naseer! I am looking forward for the release of pretrained patches! Thanks! 

> Hi Tao,
> 
> Thank you for your interest in our work.
> 
> We optimize adversarial patches by simply replacing CNN with ViTs in the following repo (https://github.com/jhayes14/adversarial-patch). We created untargeted adversarial patches.
> 
> We will release the pretrained patches as well.
> 
> Regards, Muzammal
